version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/https://github.com/JenniferGrudi/portfolio.git    
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.3.4  
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle  

      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results      

              

            
